name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ 3.9 }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pydub
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')